### ISSUE TITLE
Does cronkeep run with PHP 8.x ?

### ISSUE THREAD

**Issue by shubham8agar** [cronkeep/cronkeep#43]

**Comment by shubham8agar** [comment]
I checked and found following error lines while running cronkeep with php 8.0.6

```
----------------------------------------------------
PHP Fatal error:  Uncaught ErrorException: Undefined array key "REQUEST_METHOD" in /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Environment.php:124
Stack trace:
#0 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Environment.php(124): Slim\Slim::handleErrors()
#1 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Environment.php(76): Slim\Environment->__construct()
#2 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Slim.php(159): Slim\Environment::getInstance()
#3 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Helper/Set.php(228): Slim\Slim->Slim\{closure}()
#4 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Helper/Set.php(88): Slim\Helper\Set->Slim\Helper\{closure}()
#5 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Helper/Set.php(185): Slim\Helper\Set->get()
#6 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Slim.php(234): Slim\Helper\Set->offsetGet()
#7 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Slim.php(674): Slim\Slim->__get()
#8 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Middleware/MethodOverride.php(78): Slim\Slim->environment()
#9 /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\MethodOverride->call()
#10 /var/www/html/cronkeep/src/index.php(290): Slim\Slim->run()
#11 {main}
  thrown in /var/www/html/cronkeep/src/vendor/slim/slim/Slim/Environment.php on line 124
----------------------------------------------------
```
